### ISSUE TITLE
Document the `sort` fields for each table

### ISSUE THREAD

**Issue by phillipleblanc** [spicehq/docs#11]
## What
Document which filters can be used by queries to improve the speed of queries. If a query doesn't need to process the entire blockchain's history, then adding a filter to a specific time range cuts down on the amount of data the query needs to process and returns the result set much faster.

## Why
This improves the customer experience of using our platform by allowing them to run queries even faster.

See https://github.com/spicehq/data-platform/issues/695 for more context on why this is important.

**Comment by lukekim** [comment]
Done

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/80174/159669094-276e5da9-8ec6-4ccb-b040-a0b53b7c6e8a.png">
