### ISSUE TITLE
Docs for token specific tables

### ISSUE THREAD

**Issue by lukekim** [spicehq/docs#17]

**Comment by phillipleblanc** [comment]
Updated docs for the new NFT and tokens tables:

Tokens Tables: https://docs.spice.xyz/reference/sql-query-tables/token-tables
NFT Tables: https://docs.spice.xyz/reference/sql-query-tables/nft-tables

Example Tokens Queries: https://docs.spice.xyz/reference/example-ethereum-sql-queries/tokens
Example NFT Queries: https://docs.spice.xyz/reference/example-ethereum-sql-queries/nfts
