### ISSUE TITLE
DEX data docs

### ISSUE THREAD

**Issue by lukekim** [spicehq/docs#19]

**Comment by y-f-u** [comment]
https://app.gitbook.com/o/-Mc74Ah3rDCRYXXiWLW-/s/-Mc71sWdWMqp1e_rsTZE-129938315/~/changes/6ITkTknlLPLFspRLYZ2V/reference/sql-query-tables/ethereum/uniswap-v3-tables

**Comment by y-f-u** [comment]
@MargaretcZhang please have a look above updated doc.
