### ISSUE TITLE
ETH Core: Indexed columns are out of data, missing most tables

### ISSUE THREAD

**Issue by mitchdevenport** [spicehq/docs#26]
https://docs.spice.xyz/reference/sql-query-tables/sql-query-tables/token-tables#improving-query-performance-indexed-columns

**Comment by johnnyg** [comment]
Same for polygon

**Comment by lukekim** [comment]
This was the same for Beacon, which partially caused the livesite issue with EL. We need to fix this *and* and a checklist item to the dataset checklist.

**Comment by mitchdevenport** [comment]
> This was the same for Beacon, which partially caused the livesite issue with EL. We need to fix this _and_ and a checklist item to the dataset checklist.

@lukekim this ticket specifically refers to the indexes listed in the docs, not the actual indexes on tables

**Comment by johnnyg** [comment]
As @mitchdevenport this was doc related and completed so I'll close this. We should create a new ticket to add new indexes and add that step to the dataset checklist
