### ISSUE TITLE
Release notes for April

### ISSUE THREAD

**Issue by MargaretcZhang** [spicehq/docs#37]

**Comment by lukekim** [comment]
Market prices, especially historical prices.

**Comment by y-f-u** [comment]
do it at first week of May.

May delay TS to may update, as we can collect more performance metrics.

**Comment by mitchdevenport** [comment]
Releasing this week

**Comment by MargaretcZhang** [comment]
Github: https://github.com/spicehq/data-platform/releases/tag/v0.1-202304
GItbook: https://docs.spice.xyz/reference/release-notes
